
package scanner;

public enum TokenKind {

	EOF, UNKNOWN, ADDSUBEXP, AND, ANDCOM, ANDEXP, ANDLOGICAL, ARITHEXP, ASGNCOM, BE,
		BOOL, BOOLEXP, BOOLVARDEF, BREAK, BREAKCOM, CALL, CALLDEF, COMMAND, CMDLIST, CMDBLOCK, COMMENT, CONTINUE,
		CONTINUECOM, DECLIST, DEF, ELSE, EOL, EQUAL, EQUALB, EQUALEXP, EQUALLOGICAL, FACTOR, FALSE,
		FUNCALLCOM, FUNCDEF, FUNPRODEF, GLOBAL, GLOBALVARDEF, GT, GTE, IDENTIFIER, IF, IFCOM, INT,
		INTVARDEF, LCURL, LET, LETCOM, LPAR, LT, LTE, MULTSIGN, NOT, NOTEXP,
		NOTEQUALLOGICAL, NUMBER, NUMBERBOOLEXP, NUMBEREXP, OP_ARITMETIC,
		OP_ATTR, OP_RELATION, OREXP, ORLOGICAL, PARCALLCOM, PRINTCOM,
		PROCCALLCOM, PARAMS, PROCDEF, QUOTE, RCURL, RESULTIS, RPAR, SEMICOL, TRUE, VALOF,
		VARDEC, VARDEF, VARGLODEF, VIRG, WHILE, WHILECOM, WRITEF, PLUSSIGN, MINUSSIGN, EXPMULT, DIVSSIGN, TIMESSIGN, FUNCALLRETURN, VOID

}