
package scanner;

public enum TokenKind {

	EOF, UNKNOWN, ADDSUBEXP, AND, ANDEXP, ANDLOGICAL, ARITHEXP, ASGNCOM, BE,
		BOOL, BOOLEXP, BOOLVARDEF, BREAK, BREAKCOM, CALLCOM, COMMENT, CONTINUE,
		CONTINUECOM, ELSE, EOL, EQUAL, EQUALB, EQUALEXP, EQUALLOGICAL, FALSE,
		FUNCALLCOM, FUNCDEF, GLOBAL, GT, GTE, IDENTIFIER, IF, IFCOM, INT,
		INTVARDEF, LCURL, LET, LPAR, LT, LTE, MULDIVEXP, NOT, NOTEQUALEXP,
		NOTEQUALLOGICAL, NUMBER, NUMBERBOOLEXP, NUMBEREXP, OP_ARITMETIC,
		OP_ATTR, OP_RELATION, OREXP, ORLOGICAL, PARCALLCOM, PRINTCOM,
		PROCCALLCOM, PROCDEF, RCURL, RESULTIS, RPAR, SEMICOL, TRUE, VALOF,
		VARDCCOM, VARDEF, VARGLODEF, VIRG, WHILE, WHILECOM, WRITEF

}